Spice/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;
using Spice.Utility;

namespace Spice.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public CategoryController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await dbContext.Category.ToListAsync();
            return View(categories);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                dbContext.Add(category);
                await dbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await dbContext.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                dbContext.Update(category);
                await dbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await dbContext.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var category = await dbContext.Category.FindAsync(id);
            if (category == null)
            {
                return View();
            }
            dbContext.Category.Remove(category);
            await dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await dbContext.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
    }
}

Spice/Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;
using Spice.Utility;

namespace Spice.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public CouponController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public async Task<IActionResult> Index()
        {
            return View(await dbContext.Coupon.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupon coupons)
        {
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    coupons.Picture = p1;
                }

                dbContext.Coupon.Add(coupons);
                await dbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(coupons);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await dbContext.Coupon.FindAsync(id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Coupon coupons)
        {
            if (coupons.Id == 0)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var couponFromDb = await dbContext.Coupon.Where(x => x.Id == coupons.Id).FirstOrDefaultAsync();
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    coupons.Picture = p1;
                }

                couponFromDb.MinimumAmount = coupons.MinimumAmount;
                couponFromDb.Name = coupons.Name;
                couponFromDb.Discount = coupons.Discount;
                couponFromDb.CouponType = coupons.CouponType;
                couponFromDb.IsActive = coupons.IsActive;

                await dbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(coupons);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await dbContext.Coupon.FindAsync(id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var coupon = await dbContext.Coupon.FindAsync(id);
            if (coupon == null)
            {
                return NotFound();
            }
            return View(coupon);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var couponFromDb = await dbContext.Coupon.Where(x => x.Id == id).FirstOrDefaultAsync();
            if (couponFromDb == null)
            {
                return View();
            }
            dbContext.Coupon.Remove(couponFromDb);
            await dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Spice/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Utility;

namespace Spice.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public UserController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(await dbContext.ApplicationUser.Where(u => u.Id != claim.Value).ToListAsync());
        }

        public async Task<IActionResult> Lock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationUser = await dbContext.ApplicationUser.Where(u => u.Id == id).FirstOrDefaultAsync();
            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now.AddYears(1000);
            await dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationUser = await dbContext.ApplicationUser.Where(u => u.Id == id).FirstOrDefaultAsync();
            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now;
            await dbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Spice/Areas/Customer/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Spice.Data;
using Spice.Models;
using Spice.Models.ViewModels;
using Spice.Utility;

namespace Spice.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        [BindProperty]
        public OrderDetailsCart DetailsCart { get; set; }
        public CartController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            DetailsCart = new OrderDetailsCart
            {
                OrderHeader = new OrderHeader()
            };
            DetailsCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            var cart = dbContext.ShoppingCart.Where(u => u.ApplicationUserId == claim.Value);
            if (cart != null)
            {
                DetailsCart.ListCart = cart.ToList();
            }
            foreach (var list in DetailsCart.ListCart)
            {
                list.MenuItem = await dbContext.MenuItem.FirstOrDefaultAsync(m => m.Id == list.MenuItemId);
                DetailsCart.OrderHeader.OrderTotal += list.Count * list.MenuItem.Price;
                //list.MenuItem.Description = HttpUtility.HtmlEncode(list.MenuItem.Description);
                if (list.MenuItem.Description.Length > 100)
                {
                    list.MenuItem.Description = list.MenuItem.Description.Substring(0, 99) + "....";
                }
            }
            DetailsCart.OrderHeader.OrderTotalOriginal = DetailsCart.OrderHeader.OrderTotal;

            if (HttpContext.Session.GetString(SD.ssCouponCode) != null)
            {
                DetailsCart.OrderHeader.CouponCode = HttpContext.Session.GetString(SD.ssCouponCode);
                var couponFromDb = await dbContext.Coupon.FirstOrDefaultAsync(c => c.Name.ToLower() == DetailsCart.OrderHeader.CouponCode.ToLower());
                DetailsCart.OrderHeader.OrderTotal = SD.DiscountedPrice(couponFromDb, DetailsCart.OrderHeader.OrderTotalOriginal);
            }
            return View(DetailsCart);
        }

        public IActionResult AddCoupon()
        {
            if (DetailsCart.OrderHeader.CouponCode == null)
            {
                DetailsCart.OrderHeader.CouponCode = string.Empty;
            }
            HttpContext.Session.SetString(SD.ssCouponCode, DetailsCart.OrderHeader.CouponCode);
            return RedirectToAction("Index");
        }

        public IActionResult RemoveCoupon()
        {
            HttpContext.Session.SetString(SD.ssCouponCode, string.Empty);
            return RedirectToAction("Index");
        }
    }
}

Spice/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Create" />
    </div>
    <div class="col-6">
        <a class="btn btn-success form-control" asp-action="Index">Back To List</a>
    </div>
</div>

Spice/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i>&nbsp; Create New</a>
</p>

Spice/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" value="Delete" asp-route-id="@Model" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Spice/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <a class="btn btn-info form-control" asp-action="Edit" asp-route-id="@Model">Edit</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Spice/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Update" asp-route-id="@Model" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Back To List</a>
    </div>
</div>

Spice/Views/Shared/_Layout.cshtml
@using Spice.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spice</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-suppress-fallback-integrity="true" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <img src="~/images/mild.png" />
                    <img src="~/images/spicy.png" />
                    <img src="~/images/verySpicy.png" />
                    <label class="text-info" style="cursor:pointer">Spice</label>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="navbar-nav dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">Sub Category</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">MenuItem</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">Coupons</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">Users</a>
                                </div>
                            </li>
                        }

                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShoppingCart) != null)
                        {
                            <li style="color:white">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.GetInt32(SD.ssShoppingCart);
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li style="color:white">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp; (0)
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color:#343a40">
        <div class="container">
            &copy; 2020 - Spice
        </div>
    </footer>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Spice/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Spice/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>

        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

Spice/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MenuItem>

@if (Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Category.Name.Replace(" ",string.Empty) menu-restaurant">
        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Category.Name</h3>
        </div>

        @foreach (var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px;margin-top:10px;padding:10px;">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image" width="99%" style="border-radius:5px;border:1px solid #bbb9b9" />
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row">
                            <div class="col-8">
                                <label class="text-primary">@item.Name</label>
                                @if (item.Spicyness == "1")
                                {
                                    <img src="~/images/mild.png" title="Mild" />
                                }
                                @if (item.Spicyness == "2")
                                {
                                    <img src="~/images/spicy.png" title="Spicy" />
                                }
                                @if (item.Spicyness == "3")
                                {
                                    <img src="~/images/verySpicy.png" title="Very Spicy" />
                                }
                            </div>
                            <div class="col-4 text-right" style="color:maroon">
                                <h4>@item.Price</h4>
                            </div>
                        </div>

                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.Description)</p>
                        </div>

                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">Details</a>
                        </div>
                    </div>
                </div>
            </div>
        }
        <div class="p-4">
        </div>
    </div>
}